package com.viettel.tvbox.models.auth

data class UserInformation(
    val responseMessage: String? = null,
    val responseCode: Long? = null,
    val responseDate: String? = null,
    val id: String? = null,
    val username: String? = null,
    val email: String? = null,
    val twoFactor: String? = null,
    val msisdn: String? = null,
    val name: String? = null,
    val description: String? = null,
    val status: Int? = null,
    val type: String? = null,
    val representEmail: String? = null,
    val representMsisdn: String? = null,
    val businessCode: String? = null,
    val providerCode: String? = null,
    val providerName: String? = null,
    val nation: String? = null,
    val businessType: String? = null,
    val website: String? = null,
    val address: String? = null,
    val gender: String? = null,
    val department: String? = null,
    val changePasswordUrl: String? = null,
    val changePasswordUrlTime: Long? = null,
    val dob: String? = null,
    val forAge: String? = null,
    val roleCode: List<String>? = null,
    val permissions: List<String>? = null,
    val avatar: String? = null,
    val birthday: String? = null
)
